In [1]:
# =====================================================================
# BLOQUE 1. ARQUITECTURA DEL PROYECTO Y RUTAS RELATIVAS
# Objetivo: Crear una estructura organizada para separar datos
# originales, datos procesados, notebooks, scripts, reportes,
# visualizaciones y documentación.
# =====================================================================

import pandas as pd
from pathlib import Path

# 1. DEFINIR LA RUTA BASE DEL PROYECTO

BASE_DIR = Path.cwd()

print("Directorio base del proyecto:")
print(BASE_DIR)


# 2. DEFINIR LA ESTRUCTURA DE CARPETAS

RAW_DIR = BASE_DIR / "datos" / "originales"
PROCESSED_DIR = BASE_DIR / "datos" / "procesados"
NOTEBOOKS_DIR = BASE_DIR / "notebooks"
SCRIPTS_DIR = BASE_DIR / "scripts"
REPORTS_DIR = BASE_DIR / "reportes"
VISUALIZATIONS_DIR = BASE_DIR / "visualizaciones"
DOCS_DIR = BASE_DIR / "documentacion"


# 3. CREAR LAS CARPETAS SI NO EXISTEN

for directorio in [
    RAW_DIR,
    PROCESSED_DIR,
    NOTEBOOKS_DIR,
    SCRIPTS_DIR,
    REPORTS_DIR,
    VISUALIZATIONS_DIR,
    DOCS_DIR
]:
    directorio.mkdir(parents=True, exist_ok=True)


# 4. VERIFICAR LA CREACIÓN DE LA ESTRUCTURA

print("\nEstructura del proyecto creada correctamente.")

print("\nCarpetas principales:")
print("- Datos originales:", RAW_DIR)
print("- Datos procesados:", PROCESSED_DIR)
print("- Notebooks:", NOTEBOOKS_DIR)
print("- Scripts:", SCRIPTS_DIR)
print("- Reportes:", REPORTS_DIR)
print("- Visualizaciones:", VISUALIZATIONS_DIR)
print("- Documentación:", DOCS_DIR)

Directorio base del proyecto:
/Users/moogup/Maestria-DataScience/proyectos/Taller_Sem3_G3

Estructura del proyecto creada correctamente.

Carpetas principales:
- Datos originales: /Users/moogup/Maestria-DataScience/proyectos/Taller_Sem3_G3/datos/originales
- Datos procesados: /Users/moogup/Maestria-DataScience/proyectos/Taller_Sem3_G3/datos/procesados
- Notebooks: /Users/moogup/Maestria-DataScience/proyectos/Taller_Sem3_G3/notebooks
- Scripts: /Users/moogup/Maestria-DataScience/proyectos/Taller_Sem3_G3/scripts
- Reportes: /Users/moogup/Maestria-DataScience/proyectos/Taller_Sem3_G3/reportes
- Visualizaciones: /Users/moogup/Maestria-DataScience/proyectos/Taller_Sem3_G3/visualizaciones
- Documentación: /Users/moogup/Maestria-DataScience/proyectos/Taller_Sem3_G3/documentacion

In [2]:
# =====================================================================
# BLOQUE 2. LECTURA E INSPECCIÓN DE LOS ARCHIVOS FUENTE
# Objetivo: Leer los archivos originales, revisar su estructura,
# dimensiones, columnas, tipos de datos y valores nulos antes de
# realizar cualquier integración.
# =====================================================================


# 1. DEFINIR LAS RUTAS DE LOS ARCHIVOS ORIGINALES

ruta_master = RAW_DIR / "estudiantes_master.xlsx"
ruta_matriz = RAW_DIR / "entregas_campus_matriz.csv"
ruta_extension = RAW_DIR / "entregas_campus_extension.csv"


# 2. VERIFICAR QUE LOS ARCHIVOS EXISTAN

print("Verificación de archivos:")

print("estudiantes_master.xlsx:", ruta_master.exists())
print("entregas_campus_matriz.csv:", ruta_matriz.exists())
print("entregas_campus_extension.csv:", ruta_extension.exists())


# 3. LEER EL ARCHIVO EXCEL

df_master = pd.read_excel(
    ruta_master,
    sheet_name=0
)


# 4. LEER LOS ARCHIVOS CSV

df_matriz = pd.read_csv(
    ruta_matriz,
    encoding="utf-8"
)

df_extension = pd.read_csv(
    ruta_extension,
    encoding="utf-8"
)


# 5. REVISAR LAS DIMENSIONES DE CADA DATASET

print("\nDIMENSIONES DE LOS ARCHIVOS")

print("Maestro de estudiantes:", df_master.shape)
print("Campus matriz:", df_matriz.shape)
print("Campus extensión:", df_extension.shape)


# 6. REVISAR LOS NOMBRES DE LAS COLUMNAS

print("\nCOLUMNAS - MAESTRO")
print(df_master.columns.tolist())

print("\nCOLUMNAS - CAMPUS MATRIZ")
print(df_matriz.columns.tolist())

print("\nCOLUMNAS - CAMPUS EXTENSIÓN")
print(df_extension.columns.tolist())


# 7. VISUALIZAR LOS PRIMEROS REGISTROS

print("\nPRIMEROS REGISTROS - MAESTRO")
display(df_master.head())

print("\nPRIMEROS REGISTROS - CAMPUS MATRIZ")
display(df_matriz.head())

print("\nPRIMEROS REGISTROS - CAMPUS EXTENSIÓN")
display(df_extension.head())


# 8. REVISAR LOS TIPOS DE DATOS

print("\nTIPOS DE DATOS - MAESTRO")
print(df_master.dtypes)

print("\nTIPOS DE DATOS - CAMPUS MATRIZ")
print(df_matriz.dtypes)

print("\nTIPOS DE DATOS - CAMPUS EXTENSIÓN")
print(df_extension.dtypes)


# 9. REVISAR VALORES NULOS

print("\nVALORES NULOS - MAESTRO")
print(df_master.isnull().sum())

print("\nVALORES NULOS - CAMPUS MATRIZ")
print(df_matriz.isnull().sum())

print("\nVALORES NULOS - CAMPUS EXTENSIÓN")
print(df_extension.isnull().sum())


# 10. REVISAR DUPLICADOS EXACTOS

print("\nDUPLICADOS EXACTOS")

print("Maestro:", df_master.duplicated().sum())
print("Campus matriz:", df_matriz.duplicated().sum())
print("Campus extensión:", df_extension.duplicated().sum())

Verificación de archivos:
estudiantes_master.xlsx: True
entregas_campus_matriz.csv: True
entregas_campus_extension.csv: True

DIMENSIONES DE LOS ARCHIVOS
Maestro de estudiantes: (60, 7)
Campus matriz: (150, 7)
Campus extensión: (150, 7)

COLUMNAS - MAESTRO
['id_estudiante', 'nombre_completo', 'fecha_nacimiento', 'carrera', 'campus_origen', 'tipo_beca', 'estado_academico']

COLUMNAS - CAMPUS MATRIZ
['id_entrega', 'id_estudiante', 'fecha_subida', 'materia', 'tipo_proyecto', 'puntaje_obtenido', 'estado_entrega']

COLUMNAS - CAMPUS EXTENSIÓN
['id_entrega', 'id_estudiante', 'fecha_subida', 'materia', 'tipo_proyecto', 'puntaje_obtenido', 'estado_entrega']

PRIMEROS REGISTROS - MAESTRO

,id_estudiante,nombre_completo,fecha_nacimiento,carrera,campus_origen,tipo_beca,estado_academico
0,E001,Mateo Alvarado,1998-05-12,Ingeniería de Software,Matriz,Completa,Activo
1,E002,Camila Sánchez,2000-02-20,Ingeniería de Software,Matriz,Parcial,Activo
2,E003,Santiago Ríos,1999-03-10,Ciencias de Datos,Matriz,Ninguna,Activo
3,E004,Valentina Castro,2001-04-05,Ingeniería de Software,Extensión,Parcial,Activo
4,E005,Sebastián Ortiz,1997-05-12,Ciencias de Datos,Extensión,Ninguna,Egresado

PRIMEROS REGISTROS - CAMPUS MATRIZ

,id_entrega,id_estudiante,fecha_subida,materia,tipo_proyecto,puntaje_obtenido,estado_entrega
0,PRJ-1001,E001,2026-08-01,Sistemas de Bases de Datos,Modelado ER,95.5,Aprobado
1,PRJ-1002,E002,2026-08-02,Desarrollo de Software,Prototipo,88.0,Aprobado
2,PRJ-1003,E003,2026-08-03,DataOps,Pipeline,92.0,Aprobado
3,PRJ-1004,E006,2026-08-04,Sistemas de Bases de Datos,Script SQL,100.0,Aprobado
4,PRJ-1005,E001,2026-08-05,Desarrollo de Software,API REST,85.0,Aprobado

PRIMEROS REGISTROS - CAMPUS EXTENSIÓN

,id_entrega,id_estudiante,fecha_subida,materia,tipo_proyecto,puntaje_obtenido,estado_entrega
0,PRJ-2001,E004,2026-08-01,Sistemas de Bases de Datos,Modelado ER,88.0,Aprobado
1,PRJ-2002,E005,2026-08-02,Desarrollo de Software,Prototipo,91.0,Aprobado
2,PRJ-2003,E009,2026-08-03,DataOps,Pipeline,85.5,Aprobado
3,PRJ-2004,E010,2026-08-04,Sistemas de Bases de Datos,Script SQL,96.0,Aprobado
4,PRJ-2005,E014,2026-08-05,Desarrollo de Software,API REST,79.0,Aprobado

TIPOS DE DATOS - MAESTRO
id_estudiante                  str
nombre_completo                str
fecha_nacimiento    datetime64[us]
carrera                        str
campus_origen                  str
tipo_beca                      str
estado_academico               str
dtype: object

TIPOS DE DATOS - CAMPUS MATRIZ
id_entrega              str
id_estudiante           str
fecha_subida            str
materia                 str
tipo_proyecto           str
puntaje_obtenido    float64
estado_entrega          str
dtype: object

TIPOS DE DATOS - CAMPUS EXTENSIÓN
id_entrega              str
id_estudiante           str
fecha_subida            str
materia                 str
tipo_proyecto           str
puntaje_obtenido    float64
estado_entrega          str
dtype: object

VALORES NULOS - MAESTRO
id_estudiante       0
nombre_completo     0
fecha_nacimiento    0
carrera             0
campus_origen       0
tipo_beca           0
estado_academico    0
dtype: int64

VALORES NULOS - CAMPUS MATRIZ
id_entrega          0
id_estudiante       0
fecha_subida        0
materia             0
tipo_proyecto       0
puntaje_obtenido    6
estado_entrega      0
dtype: int64

VALORES NULOS - CAMPUS EXTENSIÓN
id_entrega          0
id_estudiante       0
fecha_subida        0
materia             0
tipo_proyecto       0
puntaje_obtenido    3
estado_entrega      0
dtype: int64

DUPLICADOS EXACTOS
Maestro: 0
Campus matriz: 0
Campus extensión: 0

In [3]:
# =====================================================================
# BLOQUE 3. INTEGRACIÓN DE LOS DATASETS
# Objetivo: Identificar la fuente de cada entrega, consolidar los dos
# campus mediante concat y cruzar las entregas con el catálogo maestro
# mediante merge.
# =====================================================================


# 1. CREAR COLUMNA PARA IDENTIFICAR EL CAMPUS DE ORIGEN

df_matriz["campus"] = "Matriz"
df_extension["campus"] = "Extension"


# 2. CONCATENAR LOS DOS ARCHIVOS DE ENTREGAS

df_entregas = pd.concat(
    [df_matriz, df_extension],
    ignore_index=True
)


# 3. VALIDAR EL RESULTADO DE LA CONCATENACIÓN

print("DIMENSIONES DESPUÉS DEL CONCAT")
print(df_entregas.shape)

print("\nREGISTROS POR CAMPUS")
print(df_entregas["campus"].value_counts())

print("\nDUPLICADOS EXACTOS DESPUÉS DEL CONCAT")
print(df_entregas.duplicated().sum())


# 4. CONVERTIR LA FECHA DE SUBIDA A TIPO FECHA

df_entregas["fecha_subida"] = pd.to_datetime(
    df_entregas["fecha_subida"],
    errors="coerce"
)

print("\nTIPO DE DATO DE fecha_subida")
print(df_entregas["fecha_subida"].dtype)

print("\nFECHAS NO CONVERTIDAS")
print(df_entregas["fecha_subida"].isnull().sum())


# 5. VALIDAR DUPLICADOS EN LA CLAVE DEL MAESTRO

duplicados_maestro = df_master["id_estudiante"].duplicated().sum()

print("\nDUPLICADOS EN id_estudiante DEL MAESTRO")
print(duplicados_maestro)


# 6. REALIZAR EL MERGE CON EL CATÁLOGO MAESTRO

df_consolidado = pd.merge(
    df_entregas,
    df_master,
    on="id_estudiante",
    how="left",
    validate="many_to_one",
    indicator=True
)


# 7. VALIDAR EL RESULTADO DEL MERGE

print("\nDIMENSIONES DESPUÉS DEL MERGE")
print(df_consolidado.shape)

print("\nRESULTADO DE CORRESPONDENCIA CON EL MAESTRO")
print(df_consolidado["_merge"].value_counts())


# 8. IDENTIFICAR CLAVES SIN CORRESPONDENCIA

sin_correspondencia = df_consolidado[
    df_consolidado["_merge"] == "left_only"
]

print("\nNÚMERO DE ENTREGAS SIN CORRESPONDENCIA EN EL MAESTRO")
print(sin_correspondencia.shape[0])

print("\nID DE ESTUDIANTES SIN CORRESPONDENCIA")
print(sin_correspondencia["id_estudiante"].unique())


# 9. REVISAR NULOS CRÍTICOS DESPUÉS DE LA INTEGRACIÓN

print("\nNULOS EN puntaje_obtenido")
print(df_consolidado["puntaje_obtenido"].isnull().sum())


# 10. VISUALIZAR LOS PRIMEROS REGISTROS DEL DATASET CONSOLIDADO

display(df_consolidado.head())

DIMENSIONES DESPUÉS DEL CONCAT
(300, 8)

REGISTROS POR CAMPUS
campus
Matriz       150
Extension    150
Name: count, dtype: int64

DUPLICADOS EXACTOS DESPUÉS DEL CONCAT
0

TIPO DE DATO DE fecha_subida
datetime64[us]

FECHAS NO CONVERTIDAS
0

DUPLICADOS EN id_estudiante DEL MAESTRO
0

DIMENSIONES DESPUÉS DEL MERGE
(300, 15)

RESULTADO DE CORRESPONDENCIA CON EL MAESTRO
_merge
both          295
left_only       5
right_only      0
Name: count, dtype: int64

NÚMERO DE ENTREGAS SIN CORRESPONDENCIA EN EL MAESTRO
5

ID DE ESTUDIANTES SIN CORRESPONDENCIA
<ArrowStringArray>
['E999', 'E888', 'E777', 'E666', 'E555']
Length: 5, dtype: str

NULOS EN puntaje_obtenido
9

,id_entrega,id_estudiante,fecha_subida,materia,tipo_proyecto,puntaje_obtenido,estado_entrega,campus,nombre_completo,fecha_nacimiento,carrera,campus_origen,tipo_beca,estado_academico,_merge
0,PRJ-1001,E001,2026-08-01,Sistemas de Bases de Datos,Modelado ER,95.5,Aprobado,Matriz,Mateo Alvarado,1998-05-12,Ingeniería de Software,Matriz,Completa,Activo,both
1,PRJ-1002,E002,2026-08-02,Desarrollo de Software,Prototipo,88.0,Aprobado,Matriz,Camila Sánchez,2000-02-20,Ingeniería de Software,Matriz,Parcial,Activo,both
2,PRJ-1003,E003,2026-08-03,DataOps,Pipeline,92.0,Aprobado,Matriz,Santiago Ríos,1999-03-10,Ciencias de Datos,Matriz,Ninguna,Activo,both
3,PRJ-1004,E006,2026-08-04,Sistemas de Bases de Datos,Script SQL,100.0,Aprobado,Matriz,Martina Vega,2000-06-18,Ingeniería de Software,Matriz,Completa,Activo,both
4,PRJ-1005,E001,2026-08-05,Desarrollo de Software,API REST,85.0,Aprobado,Matriz,Mateo Alvarado,1998-05-12,Ingeniería de Software,Matriz,Completa,Activo,both

In [4]:
# =====================================================================
# BLOQUE 4. AUTOMATIZACIÓN Y CONTROLES DE CALIDAD
# Objetivo: Automatizar validaciones de archivos, columnas, duplicados,
# claves, nulos críticos y generar un reporte de control del proceso.
# =====================================================================


# 1. VALIDAR LA EXISTENCIA DE LOS ARCHIVOS ESPERADOS

archivos_esperados = [
    ruta_master,
    ruta_matriz,
    ruta_extension
]

print("VALIDACIÓN DE ARCHIVOS")

for archivo in archivos_esperados:
    if archivo.exists():
        print(archivo.name, "- OK")
    else:
        print(archivo.name, "- NO ENCONTRADO")


# 2. DEFINIR LAS COLUMNAS ESPERADAS

columnas_master = [
    "id_estudiante",
    "nombre_completo",
    "fecha_nacimiento",
    "carrera",
    "campus_origen",
    "tipo_beca",
    "estado_academico"
]

columnas_entregas = [
    "id_entrega",
    "id_estudiante",
    "fecha_subida",
    "materia",
    "tipo_proyecto",
    "puntaje_obtenido",
    "estado_entrega"
]


# 3. VALIDAR LAS COLUMNAS DEL ARCHIVO MAESTRO

print("\nVALIDACIÓN DE COLUMNAS - MAESTRO")

faltantes_master = []

for columna in columnas_master:
    if columna not in df_master.columns:
        faltantes_master.append(columna)

if len(faltantes_master) == 0:
    print("Todas las columnas esperadas están presentes.")
else:
    print("Columnas faltantes:")
    print(faltantes_master)


# 4. VALIDAR LAS COLUMNAS DEL CAMPUS MATRIZ

print("\nVALIDACIÓN DE COLUMNAS - CAMPUS MATRIZ")

faltantes_matriz = []

for columna in columnas_entregas:
    if columna not in df_matriz.columns:
        faltantes_matriz.append(columna)

if len(faltantes_matriz) == 0:
    print("Todas las columnas esperadas están presentes.")
else:
    print("Columnas faltantes:")
    print(faltantes_matriz)


# 5. VALIDAR LAS COLUMNAS DEL CAMPUS EXTENSIÓN

print("\nVALIDACIÓN DE COLUMNAS - CAMPUS EXTENSIÓN")

faltantes_extension = []

for columna in columnas_entregas:
    if columna not in df_extension.columns:
        faltantes_extension.append(columna)

if len(faltantes_extension) == 0:
    print("Todas las columnas esperadas están presentes.")
else:
    print("Columnas faltantes:")
    print(faltantes_extension)


# 6. CALCULAR INDICADORES DE CONTROL

archivos_procesados = 3

registros_master = df_master.shape[0]
registros_matriz = df_matriz.shape[0]
registros_extension = df_extension.shape[0]

registros_entregas_leidos = registros_matriz + registros_extension

duplicados_master = df_master.duplicated().sum()
duplicados_matriz = df_matriz.duplicated().sum()
duplicados_extension = df_extension.duplicated().sum()
duplicados_consolidado = df_entregas.duplicated().sum()

duplicados_clave_master = df_master["id_estudiante"].duplicated().sum()

claves_sin_correspondencia = sin_correspondencia.shape[0]

nulos_criticos = df_consolidado["puntaje_obtenido"].isnull().sum()

fechas_no_convertidas = df_entregas["fecha_subida"].isnull().sum()

filas_salida = df_consolidado.shape[0]
columnas_salida = df_consolidado.shape[1]


# 7. GENERAR REPORTE DE CONTROL

reporte_control = pd.DataFrame({
    "indicador": [
        "Archivos procesados",
        "Registros maestro",
        "Registros campus matriz",
        "Registros campus extensión",
        "Registros de entregas leídos",
        "Duplicados maestro",
        "Duplicados campus matriz",
        "Duplicados campus extensión",
        "Duplicados después de concat",
        "Duplicados en clave del maestro",
        "Claves sin correspondencia",
        "Nulos críticos en puntaje",
        "Fechas no convertidas",
        "Filas dataset consolidado",
        "Columnas dataset consolidado"
    ],
    
    "valor": [
        archivos_procesados,
        registros_master,
        registros_matriz,
        registros_extension,
        registros_entregas_leidos,
        duplicados_master,
        duplicados_matriz,
        duplicados_extension,
        duplicados_consolidado,
        duplicados_clave_master,
        claves_sin_correspondencia,
        nulos_criticos,
        fechas_no_convertidas,
        filas_salida,
        columnas_salida
    ]
})


# 8. MOSTRAR EL REPORTE DE CONTROL

print("\nREPORTE DE CONTROL DEL PROCESO")

display(reporte_control)

VALIDACIÓN DE ARCHIVOS
estudiantes_master.xlsx - OK
entregas_campus_matriz.csv - OK
entregas_campus_extension.csv - OK

VALIDACIÓN DE COLUMNAS - MAESTRO
Todas las columnas esperadas están presentes.

VALIDACIÓN DE COLUMNAS - CAMPUS MATRIZ
Todas las columnas esperadas están presentes.

VALIDACIÓN DE COLUMNAS - CAMPUS EXTENSIÓN
Todas las columnas esperadas están presentes.

REPORTE DE CONTROL DEL PROCESO

                          indicador  valor
0               Archivos procesados      3
1                 Registros maestro     60
2           Registros campus matriz    150
3        Registros campus extensión    150
4      Registros de entregas leídos    300
5                Duplicados maestro      0
6          Duplicados campus matriz      0
7       Duplicados campus extensión      0
8      Duplicados después de concat      0
9   Duplicados en clave del maestro      0
10       Claves sin correspondencia      5
11        Nulos críticos en puntaje      9
12            Fechas no convertidas      0
13        Filas dataset consolidado    300
14     Columnas dataset consolidado     15

In [5]:
# =====================================================================
# BLOQUE 5. EXPORTACIÓN DE RESULTADOS Y CIERRE DEL FLUJO
# Objetivo: Guardar el dataset consolidado, los registros sin
# correspondencia y el reporte de calidad en las carpetas definidas.
# =====================================================================


# 1. DEFINIR LAS RUTAS DE SALIDA

ruta_consolidado = PROCESSED_DIR / "entregas_consolidadas.csv"

ruta_sin_correspondencia = REPORTS_DIR / "claves_sin_correspondencia.csv"

ruta_reporte_control = REPORTS_DIR / "reporte_control.parquet"


# 2. PREPARAR EL DATASET CONSOLIDADO PARA EXPORTACIÓN

df_salida = df_consolidado.drop(
    columns=["_merge"]
)


# 3. EXPORTAR EL DATASET CONSOLIDADO

df_salida.to_csv(
    ruta_consolidado,
    index=False,
    encoding="utf-8"
)


# 4. EXPORTAR LAS CLAVES SIN CORRESPONDENCIA

sin_correspondencia.to_csv(
    ruta_sin_correspondencia,
    index=False,
    encoding="utf-8"
)


# 5. EXPORTAR EL REPORTE DE CONTROL EN FORMATO PARQUET

reporte_control.to_parquet(
    ruta_reporte_control,
    index=False
)


# 6. VALIDAR QUE LOS ARCHIVOS FUERON GENERADOS

archivos_generados = [
    ruta_consolidado,
    ruta_sin_correspondencia,
    ruta_reporte_control
]

print("ARCHIVOS GENERADOS")

for archivo in archivos_generados:
    if archivo.exists():
        print(archivo.name, "- OK")
    else:
        print(archivo.name, "- ERROR")


# 7. REGISTRAR EL NÚMERO DE ARCHIVOS GENERADOS

numero_archivos_generados = 0

for archivo in archivos_generados:
    if archivo.exists():
        numero_archivos_generados = numero_archivos_generados + 1


print("\nNÚMERO DE ARCHIVOS GENERADOS")
print(numero_archivos_generados)


# 8. MOSTRAR RESUMEN FINAL DEL PROCESO

print("\nRESUMEN FINAL")

print("Archivos fuente procesados:", archivos_procesados)
print("Registros de entregas leídos:", registros_entregas_leidos)
print("Registros descartados:", 0)
print("Claves sin correspondencia:", claves_sin_correspondencia)
print("Nulos críticos:", nulos_criticos)
print("Dimensiones de salida:", df_salida.shape)
print("Archivos generados:", numero_archivos_generados)


# 9. MOSTRAR LAS RUTAS DE LOS RESULTADOS

print("\nRUTAS DE SALIDA")

print("Dataset consolidado:")
print(ruta_consolidado)

print("\nClaves sin correspondencia:")
print(ruta_sin_correspondencia)

print("\nReporte de control:")
print(ruta_reporte_control)

ARCHIVOS GENERADOS
entregas_consolidadas.csv - OK
claves_sin_correspondencia.csv - OK
reporte_control.parquet - OK

NÚMERO DE ARCHIVOS GENERADOS
3

RESUMEN FINAL
Archivos fuente procesados: 3
Registros de entregas leídos: 300
Registros descartados: 0
Claves sin correspondencia: 5
Nulos críticos: 9
Dimensiones de salida: (300, 14)
Archivos generados: 3

RUTAS DE SALIDA
Dataset consolidado:
/Users/moogup/Maestria-DataScience/proyectos/Taller_Sem3_G3/datos/procesados/entregas_consolidadas.csv

Claves sin correspondencia:
/Users/moogup/Maestria-DataScience/proyectos/Taller_Sem3_G3/reportes/claves_sin_correspondencia.csv

Reporte de control:
/Users/moogup/Maestria-DataScience/proyectos/Taller_Sem3_G3/reportes/reporte_control.parquet

In [6]:
import sys
print(f"Versión de Python : {sys.version.split()[0]}")
print(f"Versión de Pandas : {pd.__version__}")
print("\n¡Entorno verificado correctamente para el pipeline de datos!")

Versión de Python : 3.12.13
Versión de Pandas : 3.0.3

¡Entorno verificado correctamente para el pipeline de datos!